"""TraceRAG domain models."""

from tracerag.models.chunk import (
    ChildChunk,
    Chunk,
    ChunkMetadata,
    ParentChildChunkSet,
    ParentChunk,
)
from tracerag.models.context import (
    ContextValidationResult,
    ContextualChunk,
    ContextualChunkMetadata,
    ContextualChunkSet,
)
from tracerag.models.document import DocumentBlock, DocumentMetadata, ParsedDocument
from tracerag.models.embedding import (
    ChunkEmbeddingRecord,
    EmbeddingBatchResult,
    EmbeddingFailure,
    EmbeddingMetadata,
    EmbeddingValidationResult,
)
from tracerag.models.retrieval import (
    HybridRetrievalResult,
    RetrievalCandidate,
    RetrievalFilter,
    RetrievalQuery,
    RetrievalResult,
    RetrievalSource,
    SparseCorpusDocument,
)
from tracerag.models.vector import (
    StoredVectorRecord,
    VectorPointPayload,
    VectorSearchHit,
    VectorStorageValidationResult,
    VectorUpsertFailure,
    VectorUpsertResult,
)
from tracerag.models.manifest import IngestionManifest, ManifestEntry
from tracerag.models.types import (
    DEFERRED_EXTENSIONS,
    DISCOVERABLE_EXTENSIONS,
    EXTENSION_TO_SOURCE_KIND,
    SUPPORTED_EXTENSIONS,
    BlockType,
    CollectionName,
    ChildChunkId,
    ChunkId,
    ChunkLevel,
    ChunkNamespace,
    ContextSource,
    DiscoveryStatus,
    EmbeddingModelName,
    EmbeddingProviderName,
    EmbeddingVector,
    ParentChunkId,
    SourceKind,
    VectorPointId,
    is_deferred_extension,
    is_discoverable_extension,
    is_supported_extension,
    normalize_extension,
    source_kind_for_extension,
)

__all__ = [
    "DEFERRED_EXTENSIONS",
    "DISCOVERABLE_EXTENSIONS",
    "EXTENSION_TO_SOURCE_KIND",
    "SUPPORTED_EXTENSIONS",
    "BlockType",
    "ChildChunk",
    "ChildChunkId",
    "Chunk",
    "ChunkEmbeddingRecord",
    "CollectionName",
    "ChunkId",
    "ChunkLevel",
    "ChunkMetadata",
    "ChunkNamespace",
    "ContextSource",
    "ContextValidationResult",
    "ContextualChunk",
    "ContextualChunkMetadata",
    "ContextualChunkSet",
    "DiscoveryStatus",
    "DocumentBlock",
    "DocumentMetadata",
    "EmbeddingBatchResult",
    "EmbeddingFailure",
    "EmbeddingMetadata",
    "EmbeddingModelName",
    "EmbeddingProviderName",
    "EmbeddingValidationResult",
    "EmbeddingVector",
    "HybridRetrievalResult",
    "IngestionManifest",
    "ManifestEntry",
    "ParentChildChunkSet",
    "ParentChunk",
    "ParentChunkId",
    "ParsedDocument",
    "RetrievalCandidate",
    "RetrievalFilter",
    "RetrievalQuery",
    "RetrievalResult",
    "RetrievalSource",
    "SourceKind",
    "SparseCorpusDocument",
    "StoredVectorRecord",
    "VectorPointId",
    "VectorPointPayload",
    "VectorSearchHit",
    "VectorStorageValidationResult",
    "VectorUpsertFailure",
    "VectorUpsertResult",
    "is_deferred_extension",
    "is_discoverable_extension",
    "is_supported_extension",
    "normalize_extension",
    "source_kind_for_extension",
]
